replicaCount: 3
image:
  repository: localhost:5000/bookinfo-processor
  tag: "dev"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: EXPERIMENT
    value: true
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
