apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-bookinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookinfo
      app.kubernetes.io/instance: bookinfo
      app.kubernetes.io/name: bookinfo
  template:
    spec:
      containers:
      - name: bookinfo
        image: localhost:5000/bookinfo:dev
        env:
        - name: PORT
          value: "9090"
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
