resources:
- ../../base

# Dev-specific patches for the base resources
patchesStrategicMerge:
- deployment-patch.yaml

# ArgoCD image override to ensure dev image is used
images:
- name: localhost:5000/bookinfo
  newTag: dev
