apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base  # References the base kustomization

# Dev-specific patches for the base resources
# Ensure deployment-patch.yaml exists if you need it
# patchesStrategicMerge:
# - deployment-patch.yaml

# ArgoCD image override to ensure dev image is used
images:
- name: localhost:5000/bookinfo # This should match the repository in base/values.yaml or the charts default
  newName: localhost:5000/bookinfo # Usually the same unless changing registry
  newTag: dev

- name: localhost:5000/bookinfo-processor # This should match the repository in the processor's chart values
  newName: localhost:5000/bookinfo-processor
  newTag: dev
