apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./bookinfo-system  # Include the overlay-specific components
- ../../base/services  # Base directory with global-values.yaml

# Testing labels
commonLabels:
  environment: dev
  app.kubernetes.io/instance: bookinfo-dev
  testing: "true"

helmCharts:
  - name: bookinfo-service
    version: 1.0.7-SNAPSHOT
    repo: https://raw.githubusercontent.com/AnshuH/bookinfo-charts/main
