resources:
- ../base

# Override values for dev environment
helm:
  values:
    replicaCount: 2
    image:
      tag: dev
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    env:
      - name: ENVIRONMENT
        value: "dev"
