apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./bookinfo-system  # Include the overlay-specific components
- ../../base/services  # Base directory with global-values.yaml

# Testing labels
commonLabels:
  environment: dev
  app.kubernetes.io/instance: bookinfo-dev
