replicaCount: 3
image:
  repository: localhost:5000/bookinfo-processor
  tag: "dev"
  pullPolicy: Always
service:
  type: ClusterIP # Assuming type might still vary or want to be explicit
  # port: 80 is now inherited from the chart's default values.yaml
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

# ConfigMap settings for the processor service
configMap:
  enabled: true
  data:
    PROCESSOR_MODE: "fast"
    MAX_THREADS: "8"
    CACHE_EXPIRY: "300"
    LOG_LEVEL: "debug"
    PROCESSOR_ENV: "local"
# Environment variables now managed in global values.yaml via ConfigMap
# Any local service-specific env vars should be added here
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
