apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/bookinfo-system  # Inherits commonAnnotations

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  namespace: default
  version: 0.1.2 # Ensure this matches the chart version
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: bookinfo-service/values.yaml # Relative to this kustomization.yaml

- name: bookinfo-processor
  releaseName: bookinfo-processor
  namespace: default
  version: 0.1.2 # Ensure this matches the chart version
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: bookinfo-processor/values.yaml # Relative to this kustomization.yaml

images:
- name: localhost:5000/bookinfo-service
  newName: localhost:5000/bookinfo-service
  newTag: dev
- name: localhost:5000/bookinfo-processor
  newName: localhost:5000/bookinfo-processor
  newTag: dev

# Patches for imagePullPolicy were here, but now handled by Helm values.
