apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo-dev # Global namespace for this overlay

# Use annotations instead of labels to avoid deployment selector immutability issues
commonAnnotations:
  environment: dev
  app.kubernetes.io/instance: bookinfo-dev
  testing: "true"

resources:
  - ../../../base/services  # Base configuration with global-values.yaml

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  namespace: bookinfo-dev
  version: 1.0.7-SNAPSHOT # Updated with new books API endpoint
  repo: https://raw.githubusercontent.com/AnshuH/bookinfo-charts/main
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - ../values.yaml # Global dev overlay values
    - bookinfo-service/values.yaml # Service-specific values

- name: bookinfo-processor
  releaseName: bookinfo-processor
  namespace: bookinfo-dev
  version: 1.0.5-SNAPSHOT # Updated with ratings processing endpoint
  repo: https://raw.githubusercontent.com/AnshuH/bookinfo-charts/main
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - ../values.yaml # Global dev overlay values
    - bookinfo-processor/values.yaml # Service-specific values

# Patches for imagePullPolicy were here, but now handled by Helm values.