apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo-dev # Global namespace for this overlay

# Use annotations instead of labels to avoid deployment selector immutability issues
commonAnnotations:
  environment: dev
  app.kubernetes.io/instance: bookinfo-dev
  testing: "true"

resources:
  - ../../../base/services  # Base configuration with global-values.yaml

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  namespace: bookinfo-dev
  version: 0.1.4 # Updated with ConfigMap support
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - bookinfo-service/values.yaml

- name: bookinfo-processor
  releaseName: bookinfo-processor
  namespace: bookinfo-dev
  version: 0.1.4 # Updated with ConfigMap support
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - bookinfo-processor/values.yaml

# Patches for imagePullPolicy were here, but now handled by Helm values.