apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo-dev # Global namespace for this overlay

resources:
  - ../../../base/services/bookinfo-system  # For commonAnnotations

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  namespace: bookinfo-dev # Or remove to inherit from global
  version: 0.1.2 # Ensure this matches the chart version
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: ../../../base/services/global-values.yaml # Global defaults
  additionalValuesFiles:
    - bookinfo-service/values.yaml # Dev-specific overrides

- name: bookinfo-processor
  releaseName: bookinfo-processor
  namespace: bookinfo-dev # Or remove to inherit from global
  version: 0.1.2 # Ensure this matches the chart version
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: ../../../base/services/global-values.yaml # Global defaults
  additionalValuesFiles:
    - bookinfo-processor/values.yaml # Dev-specific overrides


# Patches for imagePullPolicy were here, but now handled by Helm values.
