apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: file:///Users/akhilcheruvalath/Harnesscore/bookinfo-config
        revision: HEAD
        directories:
          - path: overlays/*
  template:
    metadata:
      name: bookinfo-{{name}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: file:///Users/akhilcheruvalath/Harnesscore/bookinfo-config
        path: overlays/{{name}}
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: bookinfo-{{name}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
