apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-bookinfo-apps
  namespace: argocd # This root app itself lives in the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures child resources are deleted when this app is deleted
spec:
  project: default # Or your specific ArgoCD project

  source:
    repoURL: https://github.com/muralikrishnagk/bookinfo-config.git # Your config repo
    targetRevision: HEAD # Or your specific branch/tag for app definitions
    path: argocd-apps # Directory containing your child Application manifests (like bookinfo-simple-app.yaml)
    # For an App of Apps, we usually sync raw YAML manifests of Application CRs,
    # so no kustomize or helm section is needed here for the source itself.
    # If you had many app manifests and wanted to use Kustomize to manage them, you could.

  destination:
    server: https://kubernetes.default.svc # Standard for in-cluster deployment
    namespace: argocd # Child Application CRs will be created in this namespace

  syncPolicy:
    automated:
      prune: true    # Deletes child apps if their manifests are removed from Git
      selfHeal: true # Reverts cluster state to Git state if it drifts
    syncOptions:
      - CreateNamespace=true # Ensures the destination namespace (argocd) exists
