apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
  - host: bookinfo.dev.local
    http:
      paths:
      - path: /service-health-check
        pathType: Prefix
        backend:
          service:
            name: bookinfo-service-bookinfo-service
            port:
              number: 9090
