apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # Rewrite to the captured group
    # The proxy timeout annotations from before can be useful, let's keep them
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_500 http_502 http_503 http_504"
spec:
  ingressClassName: nginx
  rules:
  - host: bookinfo.example.com # Patched by overlay
    http:
      paths:
      - path: /service(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: bookinfo-service-bookinfo-service
            port:
              number: 80
      - path: /processor(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: bookinfo-processor-bookinfo-processor
            port:
              number: 80
