apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # The proxy timeout annotations from before can be useful, let's keep them
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_500 http_502 http_503 http_504"
spec:
  ingressClassName: nginx
  rules:
  - host: bookinfo.dev.local
    http:
      paths:
      - path: /service # For bookinfo-service
        pathType: Prefix
        backend:
          service:
            name: bookinfo-service-bookinfo-service
            port:
              number: 9090
      - path: /processor # For bookinfo-processor
        pathType: Prefix
        backend:
          service:
            name: bookinfo-processor-bookinfo-processor
            port:
              number: 9090
