apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # Use $1 for the first capture group from the path
    # The proxy timeout annotations from before can be useful, let's keep them
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_500 http_502 http_503 http_504"
spec:
  ingressClassName: nginx
  rules:
  - host: bookinfo.dev.local
    http:
      paths:
      - path: /service/(.*) # Path with capture group
        pathType: ImplementationSpecific # Required for regex paths
        backend:
          service:
            name: bookinfo-service-bookinfo-service
            port:
              number: 9090
      - path: /processor/(.*) # Path with capture group
        pathType: ImplementationSpecific # Required for regex paths
        backend:
          service:
            name: bookinfo-processor-bookinfo-processor
            port:
              number: 9090
