replicaCount: 2
image:
  repository: localhost:5000/bookinfo-service
  tag: "dev"
service:
  type: ClusterIP # Assuming type might still vary or want to be explicit
  # port: 80 is now inherited from the chart's default values.yaml
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
# ConfigMap settings for the service
configMap:
  enabled: true
  data:
    API_TIMEOUT: "15000"
    MAX_CONNECTIONS: "50"
    DB_POOL_SIZE: "10"
    LOG_LEVEL: "info"
    FEATURE_FLAGS: "reviews-enabled,ratings-enabled"
    SERVICE_ENV: "dev"

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
