resources:
- ../base

# Common labels for all resources
commonLabels:
  app: bookinfo
  app.kubernetes.io/name: bookinfo
  app.kubernetes.io/instance: bookinfo-prod
  environment: prod
  argocd.argoproj.io/sync-wave: "1"

# Override values for prod environment
helm:
  values:
    replicaCount: 3
    image:
      tag: prod
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
    env:
      - name: ENVIRONMENT
        value: "prod"