apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo-dev # Global namespace for this overlay

resources:
  - ../../../base/services  # Base configuration with global-values.yaml

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  namespace: bookinfo-dev
  version: 0.1.4 # Updated with ConfigMap support
  repo: http://127.0.0.1:8000
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - bookinfo-service/values.yaml

- name: bookinfo-processor
  releaseName: bookinfo-processor
  namespace: bookinfo-dev
  version: 0.1.4 # Updated with ConfigMap support
  repo: http://127.0.0.1:8000
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - bookinfo-processor/values.yaml

# Patches for imagePullPolicy were here, but now handled by Helm values.
