apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bookinfo
  labels:
    app: {{ .Release.Name }}-bookinfo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bookinfo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bookinfo
    spec:
      containers:
      - name: bookinfo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        env:
        - name: PORT
          value: "8080"
