apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bookinfo
  labels:
    app: {{ .Release.Name }}-bookinfo
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-bookinfo
