apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./bookinfo-system    # References the local bookinfo-system directory
- ../../base/services  # Base directory with global-values.yaml

# Common labels for all resources in this environment
commonLabels:
  environment: local-testing
  app.kubernetes.io/instance: bookinfo-local
