# Production values for bookinfo-service
# replicaCount: 3

image:
  repository: localhost:5000/bookinfo-service
  tag: v1.0.2
  pullPolicy: IfNotPresent # Or Always if using 'latest' or frequently changing tags

service:
  type: ClusterIP # Assuming type might still vary or want to be explicit
  # port: 80 is now inherited from the chart's default values.yaml

# ingress: # Ingress is handled by the separate infra component
#   enabled: false

# resources:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

env:
  - name: PORT
    value: "9090"
  - name: ENVIRONMENT
    value: "prod"
  # Add other prod-specific environment variables here
