# Production values for bookinfo-service
replicaCount: 3  # Higher replicas for production

image:
  repository: localhost:5000/bookinfo-service
  tag: v1.0.3-rc1  # Will be updated to v1.0.3 final in production
  # pullPolicy is now inherited from global values.yaml

service:
  type: ClusterIP
  # port: 80 is inherited from the chart's default values.yaml

resources:
  limits:
    cpu: "800m"     # Production-specific resource limits
    memory: "1024Mi"
  requests:
    cpu: "400m"
    memory: "512Mi"

env:
  - name: PORT
    value: "9090"
  # Other environment variables now come from configMap

# ConfigMap settings specific to the service
configMap:
  enabled: true
  data:
    API_TIMEOUT: "3000"  # Lower timeout for production
    MAX_CONNECTIONS: "200"  # Higher connection limit for production
    DB_POOL_SIZE: "20"  # Larger pool size for production
    LOG_LEVEL: "info"
    FEATURE_FLAGS: "reviews-enabled,ratings-enabled"
    SERVICE_ENV: "prod"
