apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///Users/akhilcheruvalath/Harnesscore/bookinfo-config
    path: argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
  resources:
    - kind: Application
      name: bookinfo-dev
      namespace: argocd
      spec:
        project: default
        source:
          repoURL: file:///Users/akhilcheruvalath/Harnesscore/bookinfo-config
          path: overlays/dev
          targetRevision: HEAD
        destination:
          server: https://kubernetes.default.svc
          namespace: bookinfo-dev
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - Validate=true
    - kind: Application
      name: bookinfo-prod
      namespace: argocd
      spec:
        project: default
        source:
          repoURL: file:///Users/akhilcheruvalath/Harnesscore/bookinfo-config
          path: overlays/prod
          targetRevision: HEAD
        destination:
          server: https://kubernetes.default.svc
          namespace: bookinfo-prod
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - Validate=true
