apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///Users/akhilcheruvalath/Harnesscore/bookinfo-config
    path: overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
