apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base # Inherits from infra/base
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: bookinfo-ingress
      # namespace: default # Optional if Ingress in base has default namespace
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: bookinfo.dev.local
