apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration for bookinfo services
# The global-values.yaml file in this directory is referenced directly by overlays
# using the valuesFile parameter in their helmCharts sections

# Generate a ConfigMap from the global-values.yaml file
# This ensures Kustomize includes the file in the build context
configMapGenerator:
- name: global-helm-values
  files:
  - global-values.yaml

resources: []  # No resources to include directly, just providing the global-values.yaml
