# QA values for bookinfo-processor
replicaCount: 2

image:
  repository: localhost:5000/bookinfo-processor
  tag: v1.0.2-rc2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # port: 80 is inherited from the chart's default values.yaml

# ingress: # Ingress is handled by the separate infra component
#   enabled: false

resources:
  limits:
    cpu: "150m"
    memory: "192Mi"
  requests:
    cpu: "75m"
    memory: "96Mi"

env:
  - name: PORT
    value: "9090"
  - name: ENVIRONMENT
    value: "qa"
  # Add other qa-specific environment variables here
