replicaCount: 2
image:
  repository: localhost:5000/bookinfo-service
  tag: "dev"
  pullPolicy: Always
service:
  type: ClusterIP # Assuming type might still vary or want to be explicit
  # port: 80 is now inherited from the chart's default values.yaml
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

# ConfigMap settings for the service
configMap:
  enabled: true
  data:
    API_TIMEOUT: "10000"
    MAX_CONNECTIONS: "20"
    DB_POOL_SIZE: "5"
    LOG_LEVEL: "info"
    FEATURE_FLAGS: "reviews-enabled,ratings-disabled"
    SERVICE_ENV: "local"

env:
  - name: ENVIRONMENT
    value: "dev"
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
