# Production values for bookinfo-processor
replicaCount: 3  # Higher replicas for production

image:
  repository: localhost:5000/bookinfo-processor
  tag: v1.0.3  # Final production release tag
  # pullPolicy is now inherited from global values.yaml

service:
  type: ClusterIP
  # port: 80 is inherited from the chart's default values.yaml

resources:
  limits:
    cpu: "800m"     # Production-specific resource limits
    memory: "1024Mi"
  requests:
    cpu: "400m"
    memory: "512Mi"

env:
  - name: PORT
    value: "9090"
  # Other environment variables now come from configMap

# ConfigMap settings specific to the processor
configMap:
  enabled: true
  data:
    PROCESSOR_MODE: "high-performance"  # Production mode
    MAX_THREADS: "16"  # Higher thread count for production
    CACHE_EXPIRY: "300"  # Longer cache expiry for production
    LOG_LEVEL: "info"
    PROCESSOR_ENV: "prod"
