# Common labels for all resources
commonLabels:
  app: bookinfo
  app.kubernetes.io/name: bookinfo
  app.kubernetes.io/instance: bookinfo

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

# Modern Kustomize v4+ Helm chart integration
helmCharts:
- name: bookinfo # This must match the chart's name in its Chart.yaml
  releaseName: bookinfo # This will be the Helm release name
  namespace: default # Namespace for the Helm release
  version: 0.1.0 # This should match the chart's version in Chart.yaml
  # Use the direct tarball URL for the chart from GitHub
  repo: https://github.com/akhilcheruvalat/bookinfo-source/raw/main/bookinfo-service/charts/bookinfo-0.1.0.tgz
  valuesFile: values.yaml # Path to your Helm values file within this Kustomize base