# Common labels for all resources
commonLabels:
  app: bookinfo
  app.kubernetes.io/name: bookinfo
  app.kubernetes.io/instance: bookinfo

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

# Using HelmChartInflationGenerator for Helm integration
# Ensure Kustomize v3.2.0+ and --enable-helm flag for ArgoCD or kustomize build
generators:
- helmChartInflationGenerator.yaml