apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: bookinfo # General app label, will be applied to pod templates
  includeSelectors: false # Default, but explicit: Do not force this into selectors
  includeTemplates: true  # Default, but explicit: Add to pod templates
# We will let the Helm chart define app.kubernetes.io/name and app.kubernetes.io/instance
# for its selectors and pod templates.

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

# Helm chart integration using the GitHub Pages repository
helmCharts:
- name: bookinfo
  releaseName: bookinfo
  namespace: default
  version: 0.1.0
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: values.yaml
