replicaCount: 1
image:
  repository: localhost:5000/bookinfo # This will be overridden by ArgoCD Kustomize image override for dev
  tag: "latest" # This will be overridden by ArgoCD Kustomize image override for dev
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
env:
  - name: ENVIRONMENT
    value: "base" # Example value
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
