apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# We assume the base for bookinfo-system might be implicitly defined by the Helm charts
# or you might have a base kustomization for bookinfo-system if common values are factored out.
# For now, we'll directly include helmCharts similar to dev.

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  version: 0.1.2 # Ensure this matches the chart version you want for prod
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: bookinfo-service/values.yaml # Prod-specific values

- name: bookinfo-processor
  releaseName: bookinfo-processor
  version: 0.1.2 # Ensure this matches the chart version you want for prod
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: bookinfo-processor/values.yaml # Prod-specific values

images:
- name: localhost:5000/bookinfo-service # Original image name from chart
  newName: localhost:5000/bookinfo-service
  newTag: v1.0.0 # Specific production tag
- name: localhost:5000/bookinfo-processor
  newName: localhost:5000/bookinfo-processor
  newTag: v1.0.0 # Specific production tag

# Example: Patches for production (e.g., replica count, resources)
# patches:
# - path: bookinfo-service-deployment-patch.yaml
#   target:
#     kind: Deployment
#     name: bookinfo-service-bookinfo-service
# - path: bookinfo-processor-deployment-patch.yaml
#   target:
#     kind: Deployment
#     name: bookinfo-processor-bookinfo-processor
